// src/components/learning/CommunityBasicsModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';

const lessons: Lesson[] = [
  { id: 0, title: "What is a Community & Why It Matters", duration: "10 min", content: { introduction: "A community is more than a neighbourhood — it is the primary unit where waste problems are felt and where solutions can be most effectively implemented.", keyPoints: ["🏘 A community shares space, resources, and consequences — waste affects everyone collectively","🇮🇳 India has 7,935 towns and 6.4 lakh villages — each a distinct community with unique waste challenges","📊 Urban communities generate 600–800g waste per person per day vs 300–400g in rural areas","🤝 Community-led initiatives are 3x more likely to succeed than top-down government programmes","👨‍👩‍👧 Social trust is the most important ingredient — communities with higher trust segregate better","🌊 The Tragedy of the Commons: shared spaces get neglected when no one feels responsible","🏙 Resident Welfare Associations (RWAs) are legally empowered to manage waste in their area","📍 Urban Local Bodies (ULBs) — municipal corporations, town panchayats — are responsible for SWM","🌱 A clean community improves property values, mental health, and civic pride","💡 Community action on waste started the Swachh Bharat Mission's citizen component in 2014"], quiz: { question: "What is the 'Tragedy of the Commons' in the context of community waste management?", options: ["When communities run out of money for waste management","When shared spaces get neglected because no individual feels personally responsible","When common waste bins are overfilled","When community leaders fail to manage waste properly"], correct: 1, explanation: "The Tragedy of the Commons describes how shared resources get degraded because each individual benefits from using them but costs are shared collectively. In waste management: a park is 'everyone's responsibility' — so it becomes 'no one's responsibility.' Community ownership and shared accountability are the antidote." } } },
  { id: 1, title: "Mapping Your Community's Waste Problem", duration: "12 min", content: { introduction: "You cannot solve a problem you haven't measured. Before taking any action, effective community leaders map their waste landscape — identifying hotspots, patterns, and root causes.", keyPoints: ["🗺 Waste mapping: walk every street and mark dumping spots and overflowing bins on a map","📸 Photo documentation: geotagged photos are powerful evidence for municipal authorities","⚖ Waste audit: weigh and categorise all waste from 10 households over 1 week","📅 Pattern analysis: most dumping happens at night; most overflow on Sundays","🏭 Source identification: identify top waste generators — markets, restaurants, construction sites","🚛 Collection gaps: map which streets get daily vs weekly vs no collection","💧 Drain contamination: identify waste blocking drains — causes flooding in monsoon","📱 Tools: Google Maps, KoboToolbox, OpenStreetMap — free for community mapping","📊 Baseline data: essential for measuring improvement after interventions","🌿 Green spots: map existing trees and gardens that need protection from waste"], quiz: { question: "Why is establishing baseline data before starting a community waste initiative important?", options: ["It is required by law","It helps identify which community members are responsible for dumping","It allows you to measure actual improvement and prove impact after your intervention","It is needed to apply for government funding"], correct: 2, explanation: "Baseline data tells you the 'before' state. Without it, you cannot measure whether your intervention actually worked. Saying 'we reduced illegal dumping incidents by 70% in 3 months compared to baseline' is compelling evidence that drives continued support and funding." } } },
  { id: 2, title: "Building a Community Waste Team", duration: "12 min", content: { introduction: "No single person can transform a community's waste habits. Effective waste management requires a dedicated team with clear roles, diverse skills, and shared commitment.", keyPoints: ["👥 Ideal team size: 8–15 people — small enough to coordinate, large enough to cover all areas","🏘 Geographic coverage: assign one team member per building/block for accountability","🎭 Key roles: Coordinator, Data Recorder, Community Liaison, Media Manager, Youth Champion","👴 Involve elders: respected community members bring credibility and historical knowledge","👩 Gender balance: women often manage household waste — their participation is crucial","🧒 Youth engagement: students are energetic, tech-savvy, and influence family behaviour","🕌 Leverage existing networks: RWAs, religious committees, school parent groups","📱 WhatsApp group: dedicated group for team communication, photos, and quick decisions","📋 Terms of reference: write down each person's role and time commitment clearly","🏆 Recognition: celebrate team achievements publicly — keeps motivation high"], quiz: { question: "Why is gender balance particularly important in a community waste management team?", options: ["Legal requirements mandate gender balance","Women manage household waste daily and have crucial insights into waste generation patterns","Women are more likely to volunteer","Gender balance improves the team's public image"], correct: 1, explanation: "Women are typically the primary managers of household waste — they decide what to buy, how to sort, and when to dispose. Their practical, daily experience is irreplaceable in designing effective solutions. Communities where women are excluded from waste planning often end up with solutions that don't work at the household level." } } },
  { id: 3, title: "Communicating Waste Issues to Your Community", duration: "10 min", content: { introduction: "Even the best waste management plan fails if the community doesn't understand or feel motivated to participate. Effective communication is the bridge between a good idea and community action.", keyPoints: ["👂 Listen first: hold 2–3 listening sessions before presenting any solution","🗣 Use local language: communicate in the language people think in, not just the official language","📱 Multi-channel: WhatsApp, notice boards, mosque/temple announcements, and door-to-door visits","📸 Show don't tell: photos of dirty areas communicate better than statistics","🎭 Storytelling: share one family's story of how proper waste management improved their life","❓ Address fears: 'Will my kabadiwala lose income?' — anticipate and answer resistance","🏆 Celebrate wins: publicly celebrate the first street to achieve 100% segregation","👶 Reach children: children influence parents — school programmes create household change","📊 Share data: monthly updates on waste reduced, bins provided, complaints resolved","🔄 Two-way communication: create easy ways for community to give feedback"], quiz: { question: "What should a community leader do BEFORE presenting a waste management solution?", options: ["Prepare detailed technical reports","Get approval from local government first","Hold listening sessions to understand community concerns and priorities","Arrange funding for the initiative"], correct: 2, explanation: "Listening before presenting is the golden rule of community organising. People support solutions they helped shape. If you present a fully-formed plan without consultation, even a good plan faces resistance because people feel it was 'done to them' not 'done with them.'" } } },
  { id: 4, title: "Starting a Community Composting Programme", duration: "15 min", content: { introduction: "Composting is one of the most impactful and achievable community waste projects. A well-managed programme can divert 50–60% of a neighbourhood's waste from landfill.", keyPoints: ["🌱 Community composting: multiple households contribute organic waste to a shared composting unit","📍 Site selection: accessible to all, away from residences (odour), near a garden","🪣 Bin types: tumbler bins (fast, clean), pit composting (cheap, large-scale), windrow (apartments)","📋 Participation rules: only clean organic waste — no plastic, no cooked non-veg (attracts rats)","👷 Compost manager: assign a dedicated person for turning, moisture management, troubleshooting","⏱ Timeline: aerobic compost ready in 45–60 days; vermicompost in 30–45 days","🌿 Compost uses: garden fertiliser, sale to nurseries (₹8–15/kg), donation to parks","📊 Impact metric: track kg of organic waste diverted monthly — motivating for participants","💰 Revenue: a 100-household composting unit can generate ₹3,000–5,000/month from compost sales","🏆 Swachh Survekshan awards extra points to cities with decentralised composting"], quiz: { question: "What is the approximate timeframe for aerobic compost to be ready for use?", options: ["1–2 weeks","45–60 days","6 months","1 year"], correct: 1, explanation: "Aerobic composting (with regular turning and adequate moisture) produces usable compost in approximately 45–60 days. The timeline depends on temperature (faster in summer), moisture, particle size, and carbon-to-nitrogen ratio. Vermicomposting is faster at 30–45 days due to worm activity." } } },
];

export const CommunityBasicsModule = () => (
  <ModuleLayout
    storageKey="community_basics_progress"
    title="Community Mobilization"
    subtitle="Beginner • 5 lessons • Certificate on completion"
    accentColor="teal"
    backTab="communities"
    nextRoute="/learning/community-intermediate"
    nextLabel="Intermediate Level"
    lessons={lessons}
  />
);
