// src/components/learning/CommunityAdvancedModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';

const lessons: Lesson[] = [
  { id: 0, title: "Working with Local Government on Waste", duration: "20 min", content: { introduction: "Municipal corporations and panchayats are legally responsible for solid waste management. Understanding how to partner with them effectively is the most powerful tool a community leader has.", keyPoints: ["🏛 ULBs: municipal corporations (large cities), municipalities (smaller), nagar panchayats (towns)","📋 SWM Rules 2016: ULBs must collect, transport, and process waste — community can hold them accountable","🗺 Ward system: your Ward Councillor is your first point of contact","📅 Ward Committee meetings: held monthly — citizens have the right to attend and raise issues","📝 Written complaints: always submit in writing — creates a paper trail and compels response","📊 RTI: file Right to Information requests to get data on waste budgets and contracts","🤝 MoU with ULB: formalise your community programme with a Memorandum of Understanding","🏆 Swachh Survekshan: your community data helps your city rank higher nationally","💰 Budget advocacy: attend public budget consultations and advocate for SWM allocations","⚖ NGT complaints: if ULB fails to act on repeated complaints, file with National Green Tribunal"], quiz: { question: "What is the most effective first step when your community has a persistent waste problem that the ULB is ignoring?", options: ["Immediately file a complaint with the National Green Tribunal","Start a social media campaign against the municipality","Submit a written complaint to the Ward Councillor and attend Ward Committee meetings","Contact national media to expose the problem"], correct: 2, explanation: "The correct escalation sequence matters. Start local — written complaints to the Ward Councillor and ULB create a paper trail. Attending Ward Committee meetings (a public right) puts the issue on record. Only if these fail repeatedly should you escalate to RTI filings, NGT complaints, or media." } } },
  { id: 1, title: "Zero Waste Community Planning", duration: "20 min", content: { introduction: "Zero Waste is not the absence of waste — it is a philosophy and planning approach that aims to eliminate waste through redesigning systems. Communities that adopt these principles achieve dramatic reductions in landfill-bound waste.", keyPoints: ["🎯 Zero Waste: divert 90%+ of waste from landfill through reduction, reuse, and recycling","🌍 Global examples: Kamikatsu, Japan — 45 categories, 80% diversion; Capannori, Italy — 82% diversion","🇮🇳 Indian examples: Mysuru, Indore, Alappuzha (Kerala) — community-driven models worth studying","📋 Zero Waste hierarchy: Rethink > Refuse > Reduce > Reuse > Repair > Recycle > Recover > Residual","🏘 Zero Waste apartment: wet waste composting, dry waste to kabadiwala, hazardous collection","🏪 Zero Waste market: reusable bags, packaging-free stalls, organic waste composting on-site","🏫 Zero Waste event: digital invites, reusable cups, compostable plates, food donation post-event","📊 Waste stream analysis: identify the top 5 waste types in your community — target those first","🤝 Extended Producer Responsibility: demand that brands take back their packaging","🏆 Zero Waste International Alliance certifies communities at 90%+ diversion"], quiz: { question: "In the Zero Waste hierarchy, which action comes BEFORE recycling in terms of priority?", options: ["Recovery (waste-to-energy)","Composting organic waste","Repair and reuse of products","Proper segregation at source"], correct: 2, explanation: "The Zero Waste hierarchy (highest to lowest priority): Rethink → Refuse → Reduce → Reuse → REPAIR → Recycle → Recover → Residual. Repair preserves all the energy and resources already embedded in a product — no reprocessing needed. Recycling, while better than landfill, still requires energy and creates some waste." } } },
  { id: 2, title: "Community Data Collection & Impact Measurement", duration: "18 min", content: { introduction: "What gets measured gets managed. Advanced community leaders collect data systematically — not just to report impact but to identify where to focus next.", keyPoints: ["📊 Key metrics: kg diverted, % households segregating, complaints resolved, cost per tonne","📅 Measurement frequency: daily (collection tracking), weekly (segregation compliance), monthly (diversion rate)","📱 Digital tools: Google Forms, KoboToolbox for surveys; Google Sheets for dashboards","📸 Photo evidence: monthly before/after comparison photos of key dumping spots","🏘 Household survey: annual 50-household survey tracks awareness, behaviour, and satisfaction","🚛 Collection tracking: note exact days and times the collection vehicle comes — accountability data","💰 Cost tracking: record all expenditures and any revenue monthly","📈 Trend analysis: is segregation compliance improving or declining? What caused the change?","🏆 Benchmarking: compare your community's metrics with similar communities in the city","📰 Impact reports: publish a simple 1-page community impact report every 6 months"], quiz: { question: "Which metric best measures the actual effectiveness of a community waste segregation programme?", options: ["Number of awareness pamphlets distributed","Number of community meetings held","Percentage of households that correctly segregate waste (compliance rate)","Total budget spent on the programme"], correct: 2, explanation: "Output metrics (pamphlets, meetings) measure activity, not impact. Outcome metrics measure actual behaviour change. The percentage of households correctly segregating waste is the most direct measure of whether the programme is actually working." } } },
  { id: 3, title: "Scaling Community Initiatives Across the City", duration: "18 min", content: { introduction: "A successful neighbourhood initiative is valuable. A model that can be replicated across an entire city is transformational. Scaling requires moving from practitioner to systems-builder.", keyPoints: ["📋 Document the model: create a clear, replicable step-by-step playbook — others can follow without you","🎓 Train other communities: offer free training workshops — builds network and scales impact exponentially","🌐 City-wide network: connect all community waste leaders in your city","📊 Comparative data: data from 20 communities is more persuasive than data from 1","🏛 Policy influence: present your model to municipal commissioner — recommend as city-wide policy","📰 Media amplification: one good news story inspires 10 other communities to start","🤝 NGO partnerships: organisations like Chintan, Toxics Link, Janaagraha help scale community models","💰 Replication funding: document cost per household — makes it easy for funders to calculate scale-up cost","🌍 National platforms: Smart Cities Mission conferences, Swachh Bharat events, India Sanitation Coalition","⚖ Institutionalisation: the ultimate scale — getting your community model written into city SWM bylaws"], quiz: { question: "What is 'institutionalisation' in the context of scaling a community waste initiative?", options: ["Getting the initiative registered as an NGO","Having the community model formally adopted into city bylaws or government policy","Moving the initiative's operations to a dedicated office","Incorporating the initiative as a social enterprise company"], correct: 1, explanation: "Institutionalisation means getting your community model formally embedded in government policy — city bylaws, municipal SWM plans, or state regulations. Indore's door-to-door segregation model, once a community initiative, was institutionalised into city policy — making it the cleanest city in India for 6 consecutive years." } } },
  { id: 4, title: "Conflict Resolution in Community Waste Management", duration: "15 min", content: { introduction: "Waste is personal — it involves daily habits, cultural practices, and economic interests. Conflict is inevitable. Leaders who can resolve conflicts effectively build stronger, more resilient communities.", keyPoints: ["⚡ Common conflicts: between kabadiwala and residents, between residents over dumping, with ragpickers","🔍 Identify root causes: conflicts often have underlying issues — fear, economic threat, disrespect","🤝 Mediation: bring conflicting parties together with a neutral facilitator","📜 Clear rules: documented, agreed-upon rules prevent conflicts before they start","⚖ Graduated sanctions: warning → fine → community service → escalation — proportionate and fair","👂 Acknowledge feelings: people need to feel heard before they can hear solutions","🔄 Restorative approach: focus on repairing harm and restoring relationships, not punishment","📸 Evidence-based: rely on documented evidence rather than accusations","🏛 Escalation path: know when to involve RWA, local councillor, or police","📋 Peace agreements: document resolutions in writing and have both parties sign"], quiz: { question: "What is the 'restorative approach' to resolving community waste conflicts?", options: ["Restoring the physical environment by cleaning up waste","Focusing on punishing violators to restore order","Focusing on repairing harm done and restoring relationships between parties","Restoring community enthusiasm after a conflict"], correct: 2, explanation: "Restorative justice focuses on repairing relationships and harm rather than punishment. Instead of fining a neighbour who dumped waste and creating a permanent enemy, a restorative approach might involve them acknowledging the harm, helping clean up, and agreeing to future behaviour — reintegrating them as a community member." } } },
  { id: 5, title: "Becoming a Community Sustainability Leader", duration: "15 min", content: { introduction: "The final lesson is about you — your role, your growth, and your impact as a community sustainability leader.", keyPoints: ["🌱 Purpose: community sustainability leaders create conditions for others to act — not just act themselves","📚 Never stop learning: waste management practices, technologies, and policies evolve rapidly","🤝 Build coalitions: no leader succeeds alone — your strength is the network you build","💪 Resilience: setbacks are inevitable — a collapsed programme, a resistant community, a funding loss","🎤 Use your voice: speak at public forums, write op-eds, testify at municipal hearings","🌍 Think globally, act locally: connect your community's actions to national sustainability goals","⚖ Advocate for equity: ensure solutions don't burden the poorest or disadvantage ragpickers","📊 Stay evidence-based: personal stories + data = most persuasive advocacy combination","🏅 Recognise others: shine the spotlight on volunteers — leadership multiplies","🌟 Legacy mindset: ask 'what will this community look like in 10 years?' and work backward from that vision"], quiz: { question: "What distinguishes a community sustainability LEADER from an ACTIVIST?", options: ["Leaders have official positions; activists are volunteers","Leaders create conditions and systems that enable others to act; activists primarily take direct action themselves","Leaders work within the system; activists challenge it","Leaders focus on long-term goals; activists focus on immediate problems"], correct: 1, explanation: "While activists primarily take direct action themselves, leaders create systems, build capacity, and enable others to act effectively. A great community waste leader doesn't just compost their own food waste — they set up a system that makes it easy for 500 households to do the same. The leader's impact multiplies through the community." } } },
];

export const CommunityAdvancedModule = () => (
  <ModuleLayout
    storageKey="community_advanced_progress"
    title="Community Sustainability Leadership"
    subtitle="Advanced • 6 lessons • Certificate on completion"
    accentColor="indigo"
    backTab="communities"
    certParam="community"
    lessons={lessons}
  />
);
