// src/components/learning/CommunityIntermediateModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';

const lessons: Lesson[] = [
  { id: 0, title: "Designing a Neighbourhood Segregation System", duration: "18 min", content: { introduction: "Getting an entire neighbourhood to segregate waste at source is one of the most impactful — and challenging — community waste projects. Success requires the right infrastructure, clear communication, and consistent follow-up.", keyPoints: ["🗑 Bin placement: one wet + one dry bin per 10 households on main walking routes","🎨 Colour coding: stick to India's standard — Green (wet), Blue (dry), Red (hazardous)","📋 Bin labels: use pictures not just text — serve diverse literacy levels","🚛 Collection schedule: communicate collection days clearly — confusion causes dumping","👷 Segregation monitors: appoint one volunteer per 20 households to check and guide","📱 QR codes on bins: link to a short video explaining what goes where — in local language","🏠 Door-to-door campaign: visit every household once before launch — explain and answer questions","📊 Tracking: record daily segregation compliance rate per street","⚠ Common failure: launching without sufficient collection infrastructure — bins fill up, system collapses","🏆 Reward streets: publicly recognise the first street to achieve 90%+ compliance"], quiz: { question: "What is the most common reason community segregation programmes fail after launch?", options: ["Community members don't understand segregation","Launching without sufficient collection infrastructure — bins fill up and the system collapses","Lack of government support","Incorrect colour coding of bins"], correct: 1, explanation: "Infrastructure mismatch is the #1 cause of failure. If wet waste bins are collected every 2 days but dry waste only weekly, people stop segregating when the dry bin overflows. Always ensure collection infrastructure matches your segregation system before the campaign launch." } } },
  { id: 1, title: "Running Effective Community Meetings", duration: "15 min", content: { introduction: "Community meetings are the engine of collective action. Well-facilitated meetings build consensus, distribute ownership, and energise participants.", keyPoints: ["📅 Timing: evenings on weekdays or Sunday mornings — avoid festival days","📍 Venue: accessible, neutral ground — not one person's house","📋 Agenda: share 24 hours in advance so people come prepared","⏱ Duration: 60–90 minutes maximum — beyond that, attention drops sharply","🗣 Facilitation: one neutral facilitator ensures all voices are heard","📝 Minutes: record decisions, action points, and who is responsible","🤫 Managing conflict: use 'I statements', focus on issues not personalities","🗳 Decision making: consensus for strategy, simple majority for operations","📱 Virtual options: WhatsApp voice calls for working members who can't attend","🔄 Follow-up: share minutes within 24 hours; check on action items at start of next meeting"], quiz: { question: "What is the recommended maximum duration for a productive community meeting?", options: ["30 minutes","60–90 minutes","2–3 hours","As long as needed"], correct: 1, explanation: "Research consistently shows that attention, energy, and productive decision-making decline sharply after 90 minutes. For community volunteers giving their free time, long meetings signal poor organisation. The most effective meetings are 60–75 minutes with a clear agenda, focused discussion, and specific action points." } } },
  { id: 2, title: "Engaging Resistant Community Members", duration: "15 min", content: { introduction: "Every community has people who resist change — sceptics, complainers, and passive non-participants. Learning to engage rather than ignore them is what separates sustainable initiatives from short-lived ones.", keyPoints: ["🔍 Understand resistance: people resist for reasons — fear, past failures, inconvenience, distrust","👂 One-on-one listening: visit resistant members personally — they often have valid concerns","📜 Address legitimate complaints: if their concern is valid, act on it — builds credibility","🤝 Find common ground: everyone wants a clean, healthy neighbourhood — start there","🏃 Early wins: show quick results in small areas — changes minds better than arguments","👑 Convert opinion leaders: one respected elder switching sides brings 20 followers","📊 Use data: before/after photos and waste reduction numbers — hard to argue with evidence","🚫 Don't shame publicly: public embarrassment creates enemies, not converts","🕐 Be patient: behavioural change takes 3–6 months on average","🔄 Re-engage: people who were resistant often become the strongest advocates after initial success"], quiz: { question: "What is the most effective strategy for handling a vocal community member who opposes your waste initiative?", options: ["Ignore them and focus on willing participants","Publicly challenge their objections at community meetings","Visit them personally to listen to their concerns and find common ground","Report them to the RWA or local authorities"], correct: 2, explanation: "Personal, private engagement is consistently the most effective approach to resistance. Visiting someone at their home shows respect and commitment. Listening without immediately defending your position helps you understand their real concerns. People who feel heard are far more likely to change their position." } } },
  { id: 3, title: "Funding Your Community Waste Project", duration: "15 min", content: { introduction: "Sustainability of community waste programmes often comes down to funding. Understanding the funding landscape is essential for community leaders.", keyPoints: ["💰 Community contribution model: ₹50–200/month per household is realistic; 50 households = ₹50,000–100,000/year","🏛 14th Finance Commission grants: ULBs receive grants specifically for SWM — communities can advocate for allocation","🌿 MGNREGS: rural communities can use job guarantee scheme for waste workers' wages","🏢 CSR funds: companies with >₹5 crore profit must spend 2% on CSR — SWM projects qualify","🌐 SBM-Urban 2.0: funds composting units, MRFs, and awareness campaigns","🏦 NABARD: finances rural SWM projects — especially composting and biogas","🌍 International: UNDP, GEF, USAID have community environment funds in India","📋 Grant writing tips: clear problem statement, measurable outcomes, realistic budget","🤝 In-kind contributions: space, labour, materials — reduce cash needs and increase ownership","📊 Financial transparency: publish monthly accounts — builds trust and attracts more contributions"], quiz: { question: "Which companies are required by Indian law to spend on CSR activities that could include waste management?", options: ["All registered companies","Only government-owned units","Companies with net profit over ₹5 crore, turnover over ₹1,000 crore, or net worth over ₹500 crore","Only multinational corporations"], correct: 2, explanation: "Under Section 135 of the Companies Act 2013, companies meeting any one of three thresholds must spend 2% of average net profit on CSR. Solid waste management, environmental sustainability, and sanitation are all eligible categories." } } },
  { id: 4, title: "Using Technology for Community Waste Management", duration: "15 min", content: { introduction: "Technology has transformed community waste management — from tracking complaints to managing collection routes. Even low-tech communities can leverage free digital tools effectively.", keyPoints: ["📱 Swachh City app: register complaints about waste directly to ULBs","🗺 Google MyMaps: free community waste mapping — mark hotspots and collection points","📊 KoboToolbox: free app for waste surveys and audits without paper forms","🤖 WhatsApp chatbots: automated responses to common questions about collection schedules","📸 Citizen science: photo-report illegal dumping via apps like FixMyStreet","🚛 GPS tracking: many municipal trucks now have GPS — track whether your area's truck actually came","💻 Google Sheets dashboard: shared spreadsheet showing daily segregation compliance by street","📡 IoT smart bins: sensors alert when bins are full — reduces overflow, optimises collection","🎮 Gamification: apps that award points for waste reporting and proper disposal","📰 Community blog: document your initiative's journey — attracts attention and support"], quiz: { question: "What is the Swachh City app primarily used for?", options: ["Tracking personal waste generation","Registering complaints about waste management issues directly to Urban Local Bodies","Finding nearest recycling centres","Managing community composting schedules"], correct: 1, explanation: "The Swachh City app allows citizens to register complaints about sanitation and waste management — including missed collection, overflowing bins, and illegal dumping — directly to their Urban Local Body. Complaints get a tracking number and are assigned to the right department for resolution." } } },
  { id: 5, title: "Sustaining Community Initiatives Long-Term", duration: "12 min", content: { introduction: "Many community waste initiatives launch with great enthusiasm but fade within 6–12 months. Sustainability requires deliberate planning — building systems, developing new leaders, and keeping the community engaged.", keyPoints: ["📚 Document everything: create a manual of your processes so successors can continue without you","👶 Leadership pipeline: always train a potential successor — don't be the single point of failure","🔄 Rotation: rotate roles every 6–12 months — prevents burnout and builds broader ownership","🏆 Annual recognition: hold a yearly Swachh Neighbour Awards event — keeps community pride high","📊 Annual report: publish a simple one-page impact report annually","🔗 Institutionalise: get your initiative formally adopted by the RWA or local body","💡 Keep innovating: introduce new elements to maintain interest","🤝 Network: connect with similar initiatives across the city","🎓 Train the trainer: enable your team members to train others — creates multiplier effect","🌱 Celebrate milestones: 6 months, 1 year, 1,000 kg diverted — make the journey worthwhile"], quiz: { question: "What is the most important thing to do to ensure a community initiative survives when the founding leader steps down?", options: ["Secure long-term government funding","Build a large social media following","Document all processes and actively develop a leadership pipeline with trained successors","Partner with a corporate sponsor"], correct: 2, explanation: "Leadership transition is the #1 reason community initiatives collapse. Documentation ensures institutional memory survives. Leadership pipeline development — identifying, training, and gradually empowering successors — ensures the initiative is never dependent on any single person." } } },
];

export const CommunityIntermediateModule = () => (
  <ModuleLayout
    storageKey="community_intermediate_progress"
    title="Local Policy & Advocacy"
    subtitle="Intermediate • 6 lessons • Certificate on completion"
    accentColor="cyan"
    backTab="communities"
    nextRoute="/learning/community-advanced"
    nextLabel="Advanced Level"
    lessons={lessons}
  />
);
