// src/components/learning/RagPickerAdvancedModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';

const lessons: Lesson[] = [
  { id: 0, title: "Using Mobile Apps to Track Income", duration: "15 min", content: { introduction: "A smartphone is the most powerful tool a waste picker can own today. Free apps can help you track daily income, find buyers, check market prices, and access government schemes.", keyPoints: ["📱 Basic income tracker: use Notes app or Google Sheets to record daily: material type, weight, price, buyer","💰 PhonePe / Google Pay / Paytm: receive payment digitally — creates a record, safer than cash","📊 Google Sheets template: weight × price = daily income; monthly total visible instantly","🗺 Google Maps: save your route, mark dealer locations, find new scrap buyers","📞 Scrap price apps: iScrap App, Scrap Monster — check today's metal and plastic prices before selling","🏛 DigiLocker: store your ID cards, vaccination records, and documents digitally","🤝 WhatsApp groups: join local waste picker and scrap dealer groups — price alerts and material exchange","📷 Photo documentation: photograph your material before selling — evidence if dispute arises","🔔 Price alerts: some dealers send WhatsApp price updates — ask to be added to their broadcast list","📚 YouTube: free tutorials in Hindi on scrap identification, price negotiation, and e-waste handling"], quiz: { question: "What is the most important reason to accept digital payments (UPI) rather than cash from scrap dealers?", options: ["Digital payments are faster","UPI payments create a permanent digital record that protects you in case of payment disputes","Cash carries germs","Digital payments earn cashback rewards"], correct: 1, explanation: "Digital payment records (via PhonePe, Google Pay etc.) create a permanent, timestamped proof of every transaction — the amount, date, and both parties' numbers. This is crucial protection if a dealer claims they paid more or less than they did. Cash transactions leave no record." } } },
  { id: 1, title: "Accessing Government Welfare Schemes", duration: "18 min", content: { introduction: "India has dozens of government schemes that waste pickers are eligible for — but most don't know about them. This lesson is a complete guide to the benefits available to you and your family right now.", keyPoints: ["🏥 PMJAY (Ayushman Bharat): ₹5 lakh/year free hospital care — check eligibility at pmjay.gov.in or call 14555","🏠 PMAY: subsidised housing loans up to ₹2.67 lakh — for BPL families","🌾 PM Ujjwala Yojana: free LPG connection for BPL families — reduces indoor air pollution","👶 ICDS (Anganwadi): free nutrition, health checkups, and early education for children under 6","📚 PM Poshan (mid-day meal): free nutritious meal for all children in government schools","💊 Jan Aushadhi Kendras: medicines at 50–90% discount — 9,000+ outlets across India","🏦 Jan Dhan account: zero-balance bank account + RuPay debit card + ₹2 lakh accident insurance","🧓 PM Shram Yogi Maandhan: pension scheme for informal workers — ₹3,000/month at age 60","📋 Registration: visit nearest Municipal Corporation office with Aadhaar card to register as waste picker","📞 Helplines: 14555 (PMJAY), 1800-11-0001 (Jan Dhan), 1800-180-1551 (PMAY)"], quiz: { question: "What does PM Shram Yogi Maandhan provide to informal workers including waste pickers?", options: ["Free health insurance up to ₹5 lakh per year","A monthly pension of ₹3,000 after reaching 60 years of age","A one-time grant of ₹1 lakh for starting a business","Free housing under PMAY"], correct: 1, explanation: "PM Shram Yogi Maandhan (PM-SYM) provides a guaranteed ₹3,000 per month pension for life after age 60 to informal workers. Waste pickers aged 18–40 can enrol by contributing a small monthly amount (₹55–200 depending on age). The government matches your contribution equally. Enrol at any Common Service Centre (CSC) with your Aadhaar card and Jan Dhan account." } } },
  { id: 2, title: "Building a Scrap Collection Business", duration: "18 min", content: { introduction: "The most successful waste pickers don't just collect — they build small businesses. By thinking like an entrepreneur, you can grow from individual collector to running a network with direct recycler relationships.", keyPoints: ["📈 Business mindset: think of yourself as a recycling micro-entrepreneur, not just a labourer","🏪 Storage space: renting a small storage unit (₹2,000–5,000/month) allows bulk accumulation for better prices","👥 Network of collectors: hire 2–3 sub-collectors, pay by weight — you aggregate, negotiate, and sell","💼 Specialisation: focus on one category (e-waste, copper, PET bottles) — builds expertise and buyer trust","🤝 Direct recycler contracts: build relationships with recycling factories — bypass dealers for better margins","📋 Business registration: register as a sole proprietorship (free, Udyam portal) — opens access to bank loans","🏦 Business loans: Mudra Yojana offers ₹50,000–10 lakh loans to informal businesses at 8–12% interest","🔧 Equipment investment: a good trolley (₹5,000), weighing scale (₹800), and baler pay back in 3 months","🌐 Online selling: register on OLX, IndiaMART — sell bulk lots to larger buyers","📊 Monthly accounts: track revenue, expenses, and profit monthly — essential for loan applications and growth"], quiz: { question: "What is the Mudra Yojana and how can waste pickers benefit from it?", options: ["A government waste collection scheme that employs waste pickers","A government loan scheme offering ₹50,000–10 lakh to informal/micro-businesses at subsidised rates","A skill development programme for waste workers","A housing scheme for BPL families"], correct: 1, explanation: "PM Mudra Yojana provides collateral-free loans to non-corporate micro and small enterprises. There are three categories: Shishu (up to ₹50,000), Kishor (₹50,000–5 lakh), and Tarun (₹5–10 lakh). Waste pickers who have Udyam registration (free online) can access Mudra loans through any bank. This enables investment in storage, better equipment, or hiring sub-collectors." } } },
];

export const RagPickerAdvancedModule = () => (
  <ModuleLayout
    storageKey="ragpicker_advanced_progress"
    title="Digital Tools & Income Tracking"
    subtitle="Advanced • 3 lessons • Certificate on completion"
    accentColor="lime"
    backTab="rag-pickers"
    certParam="ragpicker"
    lessons={lessons}
  />
);
