// src/components/learning/RagPickerBasicsModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';

const lessons: Lesson[] = [
  { id: 0, title: "Understanding Your Work & Its Importance", duration: "10 min", content: { introduction: "Waste pickers are the invisible backbone of India's recycling economy. Understanding the true value of your work is the first step to claiming the respect and rights you deserve.", keyPoints: ["♻ India's informal waste workers divert 15–20% of all urban waste from landfills every single day","💰 The informal recycling sector handles ₹17,000 crore worth of material annually","🌍 Waste pickers prevent 8–9 million tonnes of CO₂ emissions per year — equivalent to 2 million cars off the road","👥 1.5–4 million waste pickers operate across India","🏙 In Mumbai and Delhi, informal pickers recover 60–70% of recyclable dry waste","📜 SWM Rules 2016 recognise waste pickers and grant them right of first access to waste","🤝 Organisations like KKPKP (Pune) and Chintan (Delhi) represent your rights","🆔 Aadhaar-linked ID cards allow waste pickers to access government welfare schemes","💚 Your work is essential environmental service — a public good","🏆 Pune's SWaCH cooperative: waste pickers earn ₹6,000–12,000/month with formal recognition"], quiz: { question: "Approximately how much CO₂ equivalent do India's waste pickers prevent annually?", options: ["1–2 million tonnes","4–5 million tonnes","8–9 million tonnes","15–20 million tonnes"], correct: 2, explanation: "India's waste pickers prevent approximately 8–9 million tonnes of CO₂ equivalent per year. Manufacturing from recycled materials requires far less energy — recycling aluminium saves 95% of the energy needed to produce new aluminium. This makes waste pickers some of India's most effective climate change workers." } } },
  { id: 1, title: "Personal Protective Equipment (PPE)", duration: "15 min", content: { introduction: "Your body is your most important asset. The right protective equipment protects you from cuts, infections, chemicals, and long-term health damage. Many serious injuries among waste pickers are 100% preventable with proper PPE.", keyPoints: ["🧤 Thick rubber gloves: essential — protect against cuts from broken glass, needles, and chemical burns","👟 Closed-toe shoes/boots: never work barefoot — broken glass, metal, and needles cause tetanus","😷 N95 mask or cloth mask: protects against dust, fungal spores, and toxic particles","👓 Safety goggles: when sorting near batteries, chemicals, or spraying liquid waste","🦺 High-visibility vest: critical when working near roads or collection vehicles","🧥 Long-sleeved clothing: reduces skin exposure to dust, chemicals, and sharp objects","🩺 Tetanus injection: update every 5 years — essential for all waste workers handling sharp objects","💊 Hepatitis B vaccination: strongly recommended — medical waste can contain infected blood","🚿 Handwashing: wash hands with soap immediately after work, before eating, before touching face","🎒 PPE storage: keep PPE clean, dry, and separate from home items — never mix work and home clothing"], quiz: { question: "Which vaccination is most strongly recommended for waste pickers due to risk of contact with infected blood?", options: ["Typhoid vaccine","Hepatitis B vaccine","Polio vaccine","Cholera vaccine"], correct: 1, explanation: "Hepatitis B is a serious liver infection spread through contact with infected blood. It can survive outside the body for up to 7 days. Waste pickers are at high risk because they often handle mixed waste containing medical items. The Hepatitis B vaccine is highly effective (95% protection) and available free at government health centres." } } },
  { id: 2, title: "Identifying Hazardous Waste Safely", duration: "12 min", content: { introduction: "Hazardous waste can seriously injure or kill. Knowing how to identify, handle, and avoid dangerous materials is the most critical safety skill for any waste picker. When in doubt — don't touch.", keyPoints: ["⚠ NEVER handle: syringes, needles, lancets — risk of HIV, Hepatitis B/C — even with gloves","🔋 Batteries: never crush, puncture, or burn — lithium batteries can explode; lead batteries cause poisoning","🧪 Unknown liquids in bottles: never open — could be acid, pesticide, or toxic solvent","💡 CFL/fluorescent bulbs: contain mercury vapour — do not break; handle with care in sealed bag","🎨 Paint tins and chemical containers: wear gloves; avoid skin contact with residue","☢ Medical waste (red/yellow bags): do NOT open or sort — leave for authorised biomedical collectors","🔥 Gas cylinders: never attempt to open, cut, or sell scrap from gas cylinders — explosion risk","⚡ Electrical cables: check if live before handling — electrocution kills instantly","🏷 Hazard symbols: learn the GHS hazard symbols — flame, skull, corrosion, exclamation mark","📞 If you find suspicious material: do not touch — call your local municipality or 112"], quiz: { question: "You find a syringe in a bag of waste. What should you do?", options: ["Pick it up with thick gloves and put it in the hazardous waste bin","Leave it where it is — do not touch it even with gloves — and report to authorities","Place it in a plastic bottle for safe disposal","Snap off the needle and dispose of the body separately"], correct: 1, explanation: "Used syringes carry the highest risk of HIV and Hepatitis B/C transmission. Even thick gloves cannot guarantee protection against needle pricks. The correct protocol is to NEVER touch discarded syringes — not even with gloves. Leave them in place, note the location, and report to the municipality's health department." } } },
  { id: 3, title: "Health Risks & Prevention", duration: "12 min", content: { introduction: "Waste picking exposes workers to unique health risks. Understanding these risks and how to prevent them protects not just you but your family who live with you.", keyPoints: ["🦠 Infections: E. coli, Salmonella in organic waste — cause diarrhoea and vomiting","🫁 Respiratory disease: dust and toxic particles cause chronic bronchitis; open burning fumes cause cancer","☠ Heavy metal poisoning: lead (batteries), mercury (CFLs), cadmium (electronics) cause organ damage","🧪 Chemical exposure: pesticide residue, cleaning chemicals cause skin burns and long-term liver damage","🐀 Rodent contact: rats in waste carry leptospirosis — can be fatal if untreated","🌞 Heat stroke: working in direct sun near waste generates extra heat — drink 3–4 litres water per day","🔇 Hearing: compactor trucks and crushing equipment cause permanent hearing loss over time","💉 First aid: keep a basic first aid kit — antiseptic, bandages, ORS sachets, paracetamol","🏥 PMJAY (Ayushman Bharat): ₹5 lakh/year free hospital care — check eligibility at pmjay.gov.in","👨‍👩‍👧 Protect your family: shower and change clothes before entering home — children are most vulnerable to toxins"], quiz: { question: "Which government health scheme provides up to ₹5 lakh per year in free hospital care that waste workers are eligible for?", options: ["MGNREGS","PMJAY (Ayushman Bharat)","PM Kisan Yojana","ESIC scheme"], correct: 1, explanation: "PMJAY — Pradhan Mantri Jan Arogya Yojana (Ayushman Bharat) — provides free hospitalisation coverage of up to ₹5 lakh per family per year at empanelled public and private hospitals. Check eligibility at pmjay.gov.in or call 14555." } } },
  { id: 4, title: "Your Legal Rights as a Waste Worker", duration: "12 min", content: { introduction: "You have legal rights. Knowing them protects you from exploitation, harassment, and unsafe conditions. India's laws provide specific protections for informal waste workers.", keyPoints: ["📜 SWM Rules 2016: Section 4 gives waste pickers the right of first access to segregated dry waste","🆔 ID cards: municipalities must provide ID cards to registered waste pickers — demand yours","💰 Minimum wage: if contracted by municipality, you are entitled to minimum wage (₹400–600/day)","🏥 ESI: if formally employed, entitled to free medical care via Employee State Insurance","🤝 Right to form unions: waste pickers can register cooperatives under the Societies Act","🏫 Children's education: children of waste workers are entitled to free education under RTE Act","🏠 Housing: eligible for PMAY government housing schemes — many waste worker families don't know this","⚖ Protection from eviction: cannot be evicted from work sites without notice and alternative arrangement","📞 Grievance: file complaints with District Collector or State Labour Commissioner if rights are violated","🌐 Resources: Chintan.org, KKPKP Pune — national organisations that provide legal support"], quiz: { question: "Under the SWM Rules 2016, what specific right are waste pickers granted?", options: ["The right to a monthly salary from the municipality","The right of first access to segregated dry waste for collection and sale","The right to own waste collection vehicles","The right to operate waste processing facilities"], correct: 1, explanation: "Section 4 of the SWM Rules 2016 explicitly recognises waste pickers and grants them the right of first access to segregated dry waste. This means municipalities cannot contract out dry waste collection in a way that excludes existing waste pickers without providing alternative livelihoods." } } },
];

export const RagPickerBasicsModule = () => (
  <ModuleLayout
    storageKey="ragpicker_basics_progress"
    title="Safety First: Personal Protection"
    subtitle="Essential • 5 lessons • Certificate on completion"
    accentColor="orange"
    backTab="rag-pickers"
    nextRoute="/learning/ragpicker-intermediate"
    nextLabel="Intermediate Level"
    lessons={lessons}
  />
);
