// src/components/learning/RagPickerIntermediateModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';

const lessons: Lesson[] = [
  { id: 0, title: "Planning Your Collection Route", duration: "15 min", content: { introduction: "A well-planned collection route can increase your daily income by 30–50% while reducing your physical effort. Strategic route planning is the difference between struggling and thriving as a waste collector.", keyPoints: ["🗺 Map your territory: draw a simple map — mark all streets, buildings, and collection points","📅 Schedule by source: residential areas daily; offices on weekdays; markets in mornings","⏰ Timing matters: catch households before municipal collection (usually 7–10 AM) for highest quantity","🏘 Dense areas first: apartment complexes give more material per kilometre walked","🔄 Loop routes: plan circular routes so you end near your storage or dealer — avoid backtracking with full load","📊 Track your daily yield: note kg collected per route per day for 2 weeks — identify the best routes","🤝 Build relationships: households that trust you will save material separately for you","🌧 Rainy season: wet paper loses value — shift focus to metals and plastics in monsoon","🔧 Tool kit: good trolley/cart, sorting bags, weighing scale, phone for tracking — essential investments","📱 Route optimisation: Google Maps can help plan the most efficient walking route"], quiz: { question: "What is the main advantage of planning a 'loop route' for waste collection?", options: ["It covers more area than a linear route","It ensures you end near your storage or dealer, avoiding backtracking with heavy loads","It is easier to remember","Loop routes have higher waste density"], correct: 1, explanation: "A loop route (circular path) ensures you start and end at or near the same point — your storage facility or dealer. This is critical when collecting heavy materials. Efficient route planning can reduce walking distance by 20–30% while carrying full loads." } } },
  { id: 1, title: "Material Identification & Sorting", duration: "18 min", content: { introduction: "Knowing exactly what you're collecting and its market value transforms waste picking from guesswork into a skilled profession. Different materials have very different values — and mixing them reduces both value and buyer trust.", keyPoints: ["📰 Paper grades: newspaper (₹10–14/kg), cardboard (₹7–10/kg), office paper (₹12–15/kg)","🧴 Plastic types: PET bottles (₹20–30/kg), HDPE (₹15–20/kg), PP (₹10–15/kg), mixed (₹4–8/kg)","🥫 Metals: aluminium (₹90–120/kg), copper wire (₹450–550/kg), steel/iron (₹25–35/kg), brass (₹300–400/kg)","🍾 Glass: clear glass (₹1–2/kg) — low value, heavy, often not worth collecting","📱 Electronics: smartphones (₹200–500 each), laptops (₹500–2000), circuit boards (₹100–300/kg)","🔋 Batteries: lead-acid car batteries (₹80–100/kg), dry cells collected in bulk for dealers","🧵 Cloth/textile: cotton clothes (₹8–12/kg), synthetic (₹4–6/kg), torn rags (₹2–4/kg)","🔑 Sorting tip: separate each material type into individual bags — mixed material gets lowest price","💧 Dry vs wet: always dry wet paper and cardboard before selling — wet material loses value","🏷 Grade consistency: dealers pay more for consistently graded material — build reputation for quality"], quiz: { question: "Which material typically fetches the highest price per kg?", options: ["PET plastic bottles (₹20–30/kg)","Newspaper (₹10–14/kg)","Copper wire (₹450–550/kg)","Steel/iron (₹25–35/kg)"], correct: 2, explanation: "Copper wire typically fetches ₹450–550 per kg — far higher than most other recyclables. Copper is a globally traded commodity used in electrical wiring, electronics, and plumbing. Whenever you find copper items — wiring, motor coils, plumbing fittings — set them aside carefully." } } },
  { id: 2, title: "Negotiating Better Prices with Dealers", duration: "15 min", content: { introduction: "Kabadiwallas are important partners — but they are also buyers trying to maximise their profit. Knowing market rates and negotiation basics ensures you get a fair price for your hard work.", keyPoints: ["📊 Know the market rate: check scrap prices on apps like iScrap App or local WhatsApp groups daily","⚖ Weigh before selling: always weigh material on your own scale before going to dealer — compare readings","🏪 Multiple dealers: visit at least 3 dealers in your area — price differences of 15–25% are common","📦 Volume advantage: selling larger quantities (50+ kg) gives you negotiating power","✅ Grade quality: clean, well-sorted material consistently commands 10–20% premium over mixed loads","📝 Keep records: note date, material type, weight, and price received","🤝 Build relationships: regular suppliers get better prices — loyalty works both ways","💰 Cash vs credit: always demand cash payment — avoid 'udhar' (credit) with dealers when possible","📱 Digital payments: UPI payments create a record — better than cash for disputes","🏛 Cooperative advantage: cooperative members get 15–30% better prices through collective bargaining"], quiz: { question: "What is the most important practice to protect yourself from being underpaid by a scrap dealer?", options: ["Always sell to the same dealer to build loyalty","Weigh your material on your own scale before selling and compare with the dealer's scale","Sell only in the morning when dealers are in a good mood","Only sell to government-approved dealers"], correct: 1, explanation: "Scale manipulation is one of the most common ways waste pickers lose income. Dealers may calibrate their scale to read lower than actual weight. By weighing on your own scale first and comparing, you create accountability. Investing ₹500–800 in a basic digital scale is one of the best investments a waste picker can make." } } },
  { id: 3, title: "Maximising Income from Your Material", duration: "15 min", content: { introduction: "The difference between an average waste picker and a high earner is not just about how much they collect — it is about how smartly they process and sell what they collect.", keyPoints: ["🧹 Cleaning increases value: rinsed PET bottles fetch 20% more than dirty ones","✂ Preparation: flatten cardboard boxes, crush cans, strip insulation from copper wire — all increase price","🔀 Separate grades: don't mix newspaper with office paper, or PET with HDPE — separate = higher price","📦 Bulk timing: accumulate 100+ kg before selling — gives more negotiating power","🗓 Market timing: scrap prices fluctuate weekly — sell metals when prices are high, hold during dips","🏭 Direct to recycler: some recyclers buy directly from pickers, bypassing dealers — higher prices","🌐 Online platforms: Karma Recycling, Attero accept e-waste directly at better rates","♻ Value addition: sort plastic by colour — clear PET worth 30% more than green PET","🤝 Group selling: 5–10 pickers pooling material can sell at wholesale rates","💡 Specialisation: focus on one high-value material type — builds expertise and contacts"], quiz: { question: "Why does stripping insulation from copper wire before selling increase the price?", options: ["Stripped copper is lighter and easier to transport","Dealers prefer stripped copper as personal preference","Bare copper fetches a higher per-kg price because dealers don't have to do the stripping work","Stripping reveals defects that would reduce the price"], correct: 2, explanation: "Copper wire with insulation fetches ₹200–300/kg because the dealer must account for the plastic coating. Bare, stripped copper wire fetches ₹450–550/kg — more than double. By stripping yourself (using a simple blade), you capture the value-addition premium. Any processing you do that saves the dealer work is reflected in a higher price for you." } } },
];

export const RagPickerIntermediateModule = () => (
  <ModuleLayout
    storageKey="ragpicker_intermediate_progress"
    title="Efficient Collection Techniques"
    subtitle="Intermediate • 4 lessons • Certificate on completion"
    accentColor="amber"
    backTab="rag-pickers"
    nextRoute="/learning/ragpicker-advanced"
    nextLabel="Advanced Level"
    lessons={lessons}
  />
);
