// src/components/learning/StudentBasicsModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';

const lessons: Lesson[] = [
  { id: 0, title: "Why Does Waste Matter?", duration: "10 min", content: { introduction: "Waste is not just garbage — it is one of the most urgent environmental challenges of our generation. As a student, understanding why waste matters is the first step to becoming a sustainability champion.", keyPoints: ["🌍 The world generates over 2 billion tonnes of solid waste every year — enough to fill 800,000 Olympic swimming pools","🇮🇳 India generates ~62 million tonnes of waste annually; only 43% is collected and processed","📦 Single-use plastics account for 50% of all plastic waste — most used for less than 10 minutes","🏔 There are over 3,000 illegal dump sites in India alone — many near schools and water bodies","🐠 By 2050, there will be more plastic in the ocean than fish by weight if current trends continue","💸 Informal waste pickers recover ₹17,000 crore worth of recyclables annually in India","🌡 Landfills produce methane — a greenhouse gas 25x more potent than CO₂","🧑‍🎓 Youth-led clean-up campaigns have removed 10,000+ tonnes of waste globally since 2018","♻ Recycling one aluminium can saves enough energy to run a TV for 3 hours","📱 A smartphone contains over 60 different elements — many recoverable through e-waste recycling"], quiz: { question: "By 2050, what is predicted about plastic in the ocean if current trends continue?", options: ["There will be equal amounts of fish and plastic","There will be more plastic than fish by weight","Oceans will be 50% plastic by volume","Plastic will sink to the ocean floor"], correct: 1, explanation: "Studies by the Ellen MacArthur Foundation project that by 2050, the ocean will contain more plastic by weight than fish if current production and disposal patterns continue. This makes ocean plastic one of the most critical environmental issues for your generation to solve." } } },
  { id: 1, title: "Types of Waste & How to Sort Them", duration: "15 min", content: { introduction: "Not all waste is the same. Learning to identify and sort different types of waste is the most practical skill any student can develop — and it starts right in your school canteen, classroom, and home.", keyPoints: ["🟢 Wet/Organic Waste: food scraps, fruit peels, vegetable cuttings, garden clippings — goes to compost","🔵 Dry/Recyclable Waste: paper, cardboard, plastic bottles, glass jars, metal cans — goes to recycling","🔴 Hazardous Waste: batteries, paint, chemicals, fluorescent bulbs — needs special collection","🟡 E-Waste: phones, chargers, earphones, laptops, USB drives — authorised collection only","⚫ Reject Waste: soiled tissue, sanitary pads, ceramic pieces — goes to landfill (unavoidable)","🧪 Contamination: mixing waste types ruins recyclables — one greasy paper can contaminate a full batch","📏 Size matters: shred paper, flatten boxes, crush cans — reduces volume by 60-70%","🚿 Rinse rule: always rinse food containers before putting in recycling bin","📵 Screen protectors & phone cases are NOT recyclable — throw in reject waste","🔋 Never put lithium batteries in regular bins — fire hazard in garbage trucks"], quiz: { question: "What happens when you put a greasy pizza box in the recycling bin?", options: ["It gets recycled normally — grease doesn't matter","The grease is washed off at the recycling facility","It can contaminate and ruin an entire batch of recyclable paper","It just goes to a separate pile"], correct: 2, explanation: "Food grease and oil contaminate paper recycling. When wet or greasy paper enters the recycling process, it breaks down the pulp and ruins the entire batch — meaning even the clean paper around it gets rejected. Always put food-stained paper in the wet/organic bin instead." } } },
  { id: 2, title: "The 5 R's — Your Action Framework", duration: "12 min", content: { introduction: "You've heard of the 3 R's — but the full framework is 5 R's. This hierarchy tells you exactly what to do, and in what order, to minimise your waste footprint as a student.", keyPoints: ["🚫 REFUSE: Say no before waste is created — refuse straws, plastic bags, unnecessary packaging","📉 REDUCE: Buy less, use less — a student who buys fewer clothes generates 30% less textile waste","🔄 REUSE: Use items multiple times — a reusable bottle avoids ~150 plastic bottles per year","♻ RECYCLE: Process materials into new products — but only after Refuse, Reduce, Reuse fail","💡 ROT (Compost): Let organic waste decompose naturally into nutrient-rich compost","Priority order matters: Refusing is 10x better than recycling for the environment","📓 Paper notebooks: buy recycled ones — saves 17 trees per tonne of paper recycled","🎒 School bags: buy quality once vs cheap bags that break — fast fashion in stationery","🥗 Food waste: ~30% of school canteen food is thrown away — take only what you eat","💧 Water: a dripping tap wastes 15 litres/hour — report leaks to school maintenance"], quiz: { question: "In the 5 R's framework, what should be your FIRST action before anything else?", options: ["Recycle — it's the most commonly practised","Reduce — cutting consumption is most important","Refuse — preventing waste before it's created is most effective","Reuse — getting the most from what you have"], correct: 2, explanation: "REFUSE comes first in the 5 R's hierarchy. Preventing waste from being created in the first place is far more effective than any downstream management. Refusing a plastic straw eliminates that waste entirely — recycling it would still consume energy and create carbon emissions." } } },
  { id: 3, title: "Your Campus as a Sustainability Lab", duration: "15 min", content: { introduction: "Your school or college campus is the perfect place to apply sustainability principles. From the canteen to the classroom, you have more influence than you think — and many successful green initiatives started as student projects.", keyPoints: ["🏫 Campus waste audit: count and weigh all waste generated in one day — shocking for most schools","🌱 Composting unit: a 4x4 ft compost pit can handle an entire school canteen's organic waste","📦 Paper use: switching to double-sided printing reduces paper consumption by 40%","💡 Energy: leaving classrooms dark when not in use saves ₹2,000-5,000 per year per school","🚰 Water harvesting: a school with 2,000 sq m roof area can collect 1 lakh litres per monsoon","♻ Recycling corner: designated bins with clear labels increase recycling rates by 300%","🎨 Upcycling: old notebooks become art supplies; old uniforms become cleaning rags","🛒 Green canteen: replacing single-use cutlery with reusables saves 50,000 items per year","📊 Green Club: student-led environmental clubs exist in 40,000+ Indian schools","🏆 Swachh Vidyalaya Puraskar: national award recognising India's cleanest schools — your school could win"], quiz: { question: "What does a campus waste audit involve?", options: ["Checking how much money the school spends on waste collection","Counting and measuring all waste generated on campus to understand patterns","Auditing which students throw waste incorrectly","Testing the quality of recycled materials"], correct: 1, explanation: "A waste audit systematically counts, weighs, and categorises all waste generated on campus over a set period. It reveals exactly how much waste is produced, what types dominate, and where the biggest opportunities for reduction lie. Most schools are shocked by the results — and that shock drives action." } } },
  { id: 4, title: "Being a Green Ambassador", duration: "12 min", content: { introduction: "The most powerful thing a student can do is inspire others. Green Ambassadors are students who lead by example, educate their peers, and drive systemic change in their schools and communities.", keyPoints: ["📣 Peer influence: students are 3x more likely to change behaviour when asked by a peer vs a teacher","📸 Social media: a well-documented clean-up drive on Instagram reaches 10,000+ people easily","🗣 Assembly speeches: a 3-minute talk on waste can change 200 students' habits","📋 Petition power: student petitions have successfully removed single-use plastics from school canteens","🎭 Street plays (nukkad natak): a 10-minute performance reaches 500+ community members","🌳 Tree plantation: 1 tree absorbs ~22 kg of CO₂ per year — a class can plant 30 trees in an afternoon","📰 School newsletter: a monthly eco-column keeps sustainability visible and top-of-mind","🤝 NGO partnerships: organisations like Chintan, Toxics Link, and Aravali offer student volunteer programmes","🏅 National Youth Parliament: present your school's green initiative to MPs","💼 Internships: TERI, CSE, and WWF-India offer student research fellowships on sustainability"], quiz: { question: "Students are how many times more likely to change behaviour when asked by a peer compared to a teacher?", options: ["Same likelihood","2 times more likely","3 times more likely","5 times more likely"], correct: 2, explanation: "Research shows students are approximately 3x more responsive to sustainability messaging from peers than from authority figures like teachers. This is why student-led initiatives and Green Ambassador programmes are so effective at creating lasting change." } } },
];

export const StudentBasicsModule = () => (
  <ModuleLayout
    storageKey="student_basics_progress"
    title="Campus Sustainability Champion"
    subtitle="Beginner • 5 lessons • Certificate on completion"
    accentColor="green"
    backTab="students"
    nextRoute="/learning/student-intermediate"
    nextLabel="Intermediate Level"
    lessons={lessons}
  />
);
