// src/components/learning/WasteIntermediateModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';
import introVideo from '@/assets/intro.mp4';

const lessons: Lesson[] = [
  { id: 0, title: "Advanced Color Coding Systems", duration: "12 min", content: { introduction: "Beyond the basic green-blue-red system, India's national color coding has specific nuances for different settings — hospitals, construction sites, and bulk generators all follow distinct protocols.", keyPoints: ["🟢 Green: wet/organic waste — kitchen waste, garden clippings, food leftovers","🔵 Blue: dry recyclables — paper, plastic, metal, glass (clean and dry only)","🔴 Red: hazardous domestic waste — batteries, bulbs, medicines, paints, chemicals","🟡 Yellow: biomedical waste (hospitals) — human tissue, blood, bodily fluids","⚫ Black: reject waste — soiled diapers, contaminated material that cannot be recycled","🔶 Orange: biomedical mixed waste (sharps, tubing)","⚪ White: linen and non-infectious hospital waste","🏗 Construction sites: segregate concrete rubble, wood, metal, and hazardous (asbestos) separately","📦 Bulk generators (>100 units, hotels, malls): must use additional colour-coded bins on premises","📲 QR codes on bins: best practice adopted by smart cities for easy identification"], quiz: { question: "In hospital biomedical waste management, what colour bin is used for highly infectious waste like human tissue and blood?", options: ["Red","Green","Yellow","Blue"], correct: 2, explanation: "Yellow bins are used for Category 1 biomedical waste — human anatomical waste, animal waste, and soiled items heavily contaminated with blood. This colour coding follows CPCB Biomedical Waste Management Rules 2016 and ensures infectious material is routed to dedicated incineration, not regular landfills." } } },
  { id: 1, title: "Wet Waste Processing Methods", duration: "15 min", content: { introduction: "Wet/organic waste makes up 50–60% of India's municipal solid waste. Knowing how to properly process it transforms a disposal problem into a resource opportunity.", keyPoints: ["🌱 Aerobic composting: organic waste + oxygen + microbes → nutrient-rich compost in 45–60 days","🪱 Vermicomposting: earthworms break down organic waste → premium compost in 30–45 days","🦟 Black Soldier Fly (BSF): larvae consume organic waste rapidly → 2 weeks, produces insect protein","⚡ Biogas/Anaerobic digestion: organic waste in sealed tank → biogas (cooking fuel) + slurry (fertiliser)","🌡 Composting temperature: 55–65°C kills pathogens — essential for safe compost","💧 Moisture management: 40–60% moisture optimal — too wet = anaerobic smell; too dry = slow decomposition","🔄 Carbon:Nitrogen ratio: ideal is 25–30:1 — mix dry leaves (carbon) with food waste (nitrogen)","⚠ What NOT to compost: meat, dairy, oily food, diseased plants — attract pests or create odour","📊 Output: 1 kg organic waste produces ~0.25–0.35 kg compost, worth ₹5–15 in soil enrichment","🏙 Decentralised composting: apartment-scale units reduce transportation and landfill costs by 40%"], quiz: { question: "What is the ideal Carbon to Nitrogen (C:N) ratio for effective aerobic composting?", options: ["5:1","15:1","25–30:1","50:1"], correct: 2, explanation: "The optimal C:N ratio of 25–30:1 creates the perfect conditions for microbial activity to decompose organic waste efficiently. Too little carbon (low ratio) creates ammonia smell; too much carbon (high ratio) slows decomposition. Achieving this balance by mixing dry leaves/cardboard (carbon) with food waste/grass (nitrogen) produces compost in 45–60 days." } } },
  { id: 2, title: "Dry Waste Identification", duration: "15 min", content: { introduction: "Correctly identifying and sorting dry waste materials dramatically increases their recyclable value. Mixed dry waste fetches 30–50% less than properly sorted, clean material.", keyPoints: ["📰 Paper grades: newspaper, cardboard, white office paper, books — each has different value","🧴 Plastic types: look for resin identification code (1–7) embossed on bottom of containers","♳ PET (1): clear water bottles, food trays — highest value plastic ₹20–30/kg","♴ HDPE (2): milk jugs, detergent bottles, pipes — durable, easily recycled","♵ PVC (3): pipes, flooring, medical tubing — difficult to recycle, often rejected","♶ LDPE (4): plastic bags, squeezable bottles — low value, often not accepted","♷ PP (5): yogurt containers, bottle caps, straws — moderate recyclability","♸ PS (6): styrofoam, disposable cups — very low recyclability, mostly rejected","🥫 Metal: aluminium cans (highest value), steel cans, copper wire, iron/steel","🍾 Glass: separate by colour (clear, green, brown) — clean before placing in bin"], quiz: { question: "Which plastic resin code indicates PET plastic (the most commonly recycled plastic)?", options: ["♳ Code 1","♴ Code 2","♷ Code 5","♸ Code 6"], correct: 0, explanation: "PET (Polyethylene Terephthalate) is marked with the ♳ resin code 1 on the bottom of containers. It includes clear water bottles, fizzy drink bottles, and food trays. PET has the highest recycling rate among plastics because it can be cleanly processed into fibres for clothing, new bottles, and packaging." } } },
  { id: 3, title: "Hazardous Material Recognition", duration: "12 min", content: { introduction: "Household hazardous waste (HHW) is far more common than most people realise — it hides in medicine cabinets, garages, and kitchens. Recognising and handling it correctly prevents serious environmental and health harm.", keyPoints: ["🔋 Batteries: ALL types (AA, AAA, lithium, lead-acid) — never in regular bins, never in fire","💡 Fluorescent lights & CFLs: contain mercury — handle unbroken, return to collection points","🧴 Cleaning chemicals: bleach, ammonia, acids — never mix, always keep in original containers","🎨 Paint: liquid paint is hazardous; dried paint is generally safe for regular waste","🌿 Pesticides & herbicides: even empty containers have residue — return to authorised collection","💊 Medicines: unused or expired medicines — return to pharmacy, never flush down drain","📱 Electronics: lead, cadmium, mercury in circuit boards — use e-waste collection centres","🚗 Motor oil: 1 litre contaminates 1 million litres of groundwater — return to auto shops","⚠ GHS symbols to know: flame (flammable), skull/crossbones (toxic), corrosion (corrosive), exclamation (irritant)","📞 CPCB authorised e-waste recyclers: list available at cpcb.nic.in — use only authorised collectors"], quiz: { question: "Where should unused or expired medicines be disposed of?", options: ["Flushed down the toilet or drain","Returned to a pharmacy or authorised medicine take-back programme","Placed in the green organic waste bin","Buried in soil in the garden"], correct: 1, explanation: "Unused medicines must never be flushed (they contaminate waterways and harm aquatic life) or thrown in regular bins (they can be found and misused). The safest disposal is returning to a pharmacy — many now accept unused medicines under Extended Producer Responsibility schemes." } } },
  { id: 4, title: "Industrial Waste Categories", duration: "15 min", content: { introduction: "Industrial waste differs fundamentally from household waste in scale, composition, and regulatory requirements. Understanding industrial waste categories is essential for any waste management professional.", keyPoints: ["🏭 Schedule I (non-hazardous industrial): fly ash, slag, ETP sludge — can be co-processed or landfilled","⚠ Schedule II (hazardous): defined under Hazardous Waste Management Rules 2016 — 18 categories","☢ E-waste: largest fastest-growing hazardous category — 53.6 million tonnes globally in 2019","🧪 Chemical waste: spent solvents, acids, alkalis, catalysts — require neutralisation or incineration","🏗 Construction & Demolition (C&D): 530 million tonnes/year in India — concrete, metal, wood","🔩 Metal scrap: mostly recyclable but may contain toxic coatings or alloys requiring treatment","🌿 Organic industrial waste: food processing, leather, textile — high BOD, requires treatment","⚡ Fly ash: coal power plant byproduct — 200 million tonnes/year in India, usable in cement/bricks","📋 Consent to Operate: all industrial units must hold CPCB/SPCB consent for waste disposal","📊 Manifest system: hazardous waste must be tracked from generator to disposal with Form 9 manifest"], quiz: { question: "What is the 'manifest system' in industrial hazardous waste management?", options: ["A list of all industrial units that generate hazardous waste","A tracking document that follows hazardous waste from generator to final disposal facility","The annual environmental compliance report filed by industries","A permit required before constructing a waste treatment facility"], correct: 1, explanation: "The manifest (Form 9 under HWM Rules) is a chain-of-custody document that tracks hazardous waste from the point of generation through transport to the final treatment/disposal facility. Every transfer must be documented and signed. This prevents illegal dumping by ensuring accountability at every step." } } },
  { id: 5, title: "Medical Waste Protocols", duration: "12 min", content: { introduction: "Biomedical waste is generated by hospitals, clinics, labs, and even households with diabetic patients. Improper management spreads infections and contaminates the environment — proper protocols are critical.", keyPoints: ["🏥 Biomedical Waste Management Rules 2016: all healthcare facilities must register with SPCB","🟡 Yellow bag: human anatomical waste, animal body parts, blood-soaked items — incinerate","🔴 Red bag: contaminated waste, tubing, catheters, used gloves — autoclave then shred","⚪ White container: sharps — needles, blades, broken glass — must use puncture-proof containers","🔵 Blue bag: glass vials, ampoules — disinfect then recycle","💉 Sharps safety: never recap needles; never fill sharps container beyond ¾; destroy before disposal","🏠 Home healthcare waste (needles, test strips): use sharps container, return to pharmacy","🚑 Common Treatment Facilities (CTFs): centralised facilities that treat waste for multiple hospitals","📊 India: 600,000+ healthcare facilities generate ~600 tonnes biomedical waste daily","⚖ Penalty: improper biomedical waste disposal carries up to ₹1 lakh fine under BMW Rules 2016"], quiz: { question: "What must be done with sharps (needles, blades) before they are disposed of in healthcare settings?", options: ["They can be placed directly in any rigid container","They must be placed in dedicated puncture-proof sharps containers and destroyed before final disposal","They should be bent or broken to prevent reuse","They go in the yellow incineration bag along with anatomical waste"], correct: 1, explanation: "Sharps must be collected in dedicated white, puncture-proof, leak-proof containers. Containers must not be filled beyond ¾ capacity. Before final disposal, sharps must be rendered unusable through needle destroyers or autoclaving+shredding at authorised Common Treatment Facilities." } } },
];

export const WasteIntermediateModule = () => (
  <ModuleLayout
    storageKey="intermediate_progress"
    title="Advanced Segregation Techniques"
    subtitle="Intermediate • 6 lessons • Certificate on completion"
    accentColor="blue"
    backTab="core-training"
    nextRoute="/learning/waste-processing"
    nextLabel="Advanced Level"
    introVideo={introVideo}
    lessons={lessons}
  />
);
