// src/components/learning/WasteAdvanceModule.tsx
import React from 'react';
import { ModuleLayout, Lesson } from './ModuleLayout';
import advancedVideo from '@/assets/advancedIntro.mp4';

const lessons: Lesson[] = [
  { id: 0, title: "Waste Treatment Technologies", duration: "18 min", content: { introduction: "Modern waste management goes far beyond landfilling. A range of treatment technologies can convert waste into energy, recover materials, and neutralise hazardous substances.", keyPoints: ["🔥 Incineration: burns waste at 850–1100°C, reduces volume by 90%, generates electricity","♻ Mechanical Biological Treatment (MBT): sorts and treats mixed waste before landfill","⚡ Plasma gasification: ultra-high temperature converts waste to syngas — most advanced tech","🌱 Anaerobic digestion: produces biogas from organic waste — used at city scale in Europe","🏗 Refuse Derived Fuel (RDF): processed waste pellets used as fuel in cement kilns","🧪 Chemical treatment: neutralises acids/alkalis; oxidation for organic contaminants","🌊 Stabilisation/solidification: hazardous waste encapsulated in cement for safe landfill","📊 MRFs (Material Recovery Facilities): mechanically sort dry recyclables with conveyors, magnets, optical sorters","🇮🇳 India's challenge: most cities still use open dumping — only 20% waste gets treated","💡 Decentralised solutions: better for India than large centralised plants — fewer transportation emissions"], quiz: { question: "What technology uses ultra-high temperatures to convert waste into syngas?", options: ["Incineration","Plasma gasification","Anaerobic digestion","Mechanical Biological Treatment"], correct: 1, explanation: "Plasma gasification uses plasma torches to generate temperatures of 3,000–10,000°C — hotter than the surface of the sun. This converts any waste (including hazardous) into syngas (hydrogen + carbon monoxide) that can generate electricity. It produces virtually no toxic emissions compared to incineration, but is expensive and energy-intensive to operate." } } },
  { id: 1, title: "Recycling Industry Overview", duration: "15 min", content: { introduction: "Recycling is a global industry worth over $500 billion annually. Understanding its economics, challenges, and opportunities is essential for waste management professionals.", keyPoints: ["💰 Global recycling market: $500+ billion annually and growing at 5% per year","🇮🇳 India's recycling sector: largely informal — 95% of dry waste recycling done by informal sector","📉 Commodity prices: recycling viability depends on global commodity markets — prices fluctuate widely","🖨 Paper: India recycles ~27% of paper; 1 tonne recycled saves 17 trees and 50% energy","🧴 Plastic: only 9% of all plastic ever produced has been recycled globally","🔩 Metals: steel is most recycled material globally (80%+); aluminium saves 95% energy vs virgin","🍾 Glass: can be recycled infinitely without quality loss; saves 30% energy per cycle","📱 E-waste recycling: India generates 3.2 million tonnes/year; only 20% formally recycled","🌐 China's National Sword policy (2018): banned import of mixed recyclables — disrupted global recycling","⚖ Extended Producer Responsibility (EPR): manufacturers legally responsible for end-of-life of products"], quiz: { question: "What percentage of all plastic ever produced globally has been recycled?", options: ["9%","25%","50%","70%"], correct: 0, explanation: "Only 9% of all plastic ever produced has been recycled. 12% has been incinerated and a staggering 79% has accumulated in landfills or the natural environment. This is because most plastic types are expensive to sort and process, and commodity prices are often too low to make recycling economically viable." } } },
  { id: 2, title: "Material Recovery Facilities", duration: "15 min", content: { introduction: "Material Recovery Facilities (MRFs) are the industrial backbone of dry waste recycling. Understanding how they work helps waste professionals maximise the quality and quantity of material they deliver.", keyPoints: ["🏭 MRF function: receives, sorts, processes, and bales dry recyclables for sale to recyclers","📦 Input: single-stream (all recyclables mixed) or sorted (pre-segregated by type)","🔄 Sorting line: tipping floor → pre-sort → screens → air classifiers → magnets → optical sorters → manual QC","🧲 Magnetic separation: removes ferrous metals (iron, steel) from mixed stream","⚡ Eddy current separator: separates non-ferrous metals (aluminium) from plastic/paper","💡 Near-Infrared (NIR) optical sorters: identify plastic types by molecular signature → automated air jets","📊 Output purity: high-quality MRFs achieve 95%+ purity per material stream","💰 Revenue: MRF earns from sale of baled material — aluminium (₹90–120/kg), paper (₹10–14/kg)","🇮🇳 India: ~800 MRFs operational, mostly small-scale; only 5% meet international quality standards","⚠ Contamination impact: 10% contamination reduces bale value by 30–50%"], quiz: { question: "What technology do advanced MRFs use to automatically identify and separate different plastic types?", options: ["Magnetic separation","Eddy current separators","Near-Infrared (NIR) optical sorters","Air classifiers"], correct: 2, explanation: "NIR (Near-Infrared) optical sorters shine infrared light on materials moving along a conveyor. Different plastics absorb NIR light at unique wavelengths — PET looks different from HDPE from PP. The sensor identifies the material type in milliseconds and triggers a jet of compressed air to divert it to the correct chute." } } },
  { id: 3, title: "Circular Economy Principles", duration: "18 min", content: { introduction: "The Circular Economy represents the most significant shift in how we think about materials and products since the Industrial Revolution. It is both a business framework and an environmental imperative.", keyPoints: ["⭕ Core principle: keep materials in use at their highest value for as long as possible","🔄 Biological cycle: organic materials return to biosphere safely through composting/digestion","🔩 Technical cycle: manufactured products and materials recovered and regenerated","🛠 Design for circularity: products designed to be repaired, remanufactured, or recycled from the start","📦 Packaging design: mono-materials, recyclable inks, no mixed-material laminates","💼 Business models: product-as-a-service, leasing, take-back schemes, remanufacturing","🇮🇳 India's CE opportunity: NITI Aayog estimates ₹40 lakh crore GDP opportunity by 2050","🌿 Regenerative agriculture: closing the loop on food — organic waste becomes soil amendment","📊 Ellen MacArthur Foundation: leading global CE research","🏭 Industrial symbiosis: Kalundborg Symbiosis (Denmark) — 12 companies share waste/energy streams"], quiz: { question: "What is 'design for circularity' in product manufacturing?", options: ["Designing products with circular shapes","Designing products from the start to be easily repaired, remanufactured, or recycled","Designing a circular business model","Designing products that complete a circular journey from factory to customer"], correct: 1, explanation: "Design for circularity means embedding end-of-life considerations into a product's design from day one — using mono-materials, standardised components that can be replaced, modular design for easy disassembly, and avoiding mixed-material composites that are impossible to separate for recycling." } } },
  { id: 4, title: "Environmental Impact Assessment", duration: "15 min", content: { introduction: "Environmental Impact Assessment (EIA) is the systematic process of evaluating the environmental consequences of proposed projects. In waste management, EIA is mandatory for large facilities.", keyPoints: ["📋 EIA definition: predicts and evaluates environmental impacts of a proposed project before approval","⚖ Legal basis: EIA Notification 2006 under Environment Protection Act 1986","🏭 Waste projects requiring EIA: landfills >2 lakh tonnes/year, incinerators, large MRFs","📊 Scoping: identifying significant environmental impacts to be studied in detail","🔬 Baseline study: measuring existing environmental conditions before project begins","💨 Impact prediction: modelling air, water, soil, noise, and social impacts","🌿 Mitigation measures: actions to reduce, avoid, or compensate for identified impacts","👥 Public hearing: mandatory consultation with local communities — their objections are formally recorded","📝 EIA report: submitted to MoEFCC (Ministry of Environment) for clearance","⚠ Post-clearance monitoring: continuous monitoring of actual vs predicted impacts after commissioning"], quiz: { question: "What is the purpose of a 'public hearing' in the EIA process?", options: ["To allow the public to vote on whether a project should proceed","To formally record local community views, concerns, and objections about a proposed project","To present the completed EIA report to government officials","To gather data on public willingness to pay for environmental services"], correct: 1, explanation: "The public hearing is a mandatory step where the project proponent presents findings to affected local communities who can formally register support or objections. All concerns raised are recorded in the official minutes and the EIA authority must address them before granting or rejecting environmental clearance." } } },
  { id: 5, title: "Policy & Regulations in India", duration: "15 min", content: { introduction: "India has a comprehensive framework of environmental legislation. Understanding these laws empowers waste management professionals to drive compliance and accountability.", keyPoints: ["📜 Environment Protection Act 1986: umbrella law — government can make any regulation needed","🗑 SWM Rules 2016: mandates source segregation, bans littering, defines ULB responsibilities","🛍 Plastic Waste Management Rules 2021: bans 19 categories of SUP from July 2022; EPR for all plastic producers","💻 E-Waste Management Rules 2022: PRO system; 60% collection target by 2023","🔋 Battery Waste Management Rules 2022: EPR for all battery manufacturers and importers","🏭 Hazardous Waste Management Rules 2016: 18 hazardous categories; manifest system; TSDF facilities","🌿 Bio-Medical Waste Rules 2016: colour-coded bags; CTF system; all HCFs must register","🏗 C&D Waste Rules 2016: bulk generators must manage own C&D waste","⚖ National Green Tribunal Act 2010: specialised court — issues binding orders on polluters","📊 Swachh Bharat Mission Urban 2.0: ₹1.41 lakh crore investment in ULB solid waste infrastructure"], quiz: { question: "What does EPR (Extended Producer Responsibility) mean in the context of plastic waste rules?", options: ["Producers must pay an extra tax on plastic products sold","Producers are legally responsible for collecting and recycling the plastic packaging they put into the market","Producers must use extended (longer-lasting) plastic materials","Producers must provide extended warranties on plastic products"], correct: 1, explanation: "EPR makes the original producer legally and financially responsible for the end-of-life management of their products and packaging. Under India's PWM Rules 2021, plastic producers must either directly collect and recycle the plastic they sell (in kg equivalent) or pay into a fund that finances recycling." } } },
];

export const WasteAdvancedModule = () => (
  <ModuleLayout
    storageKey="advanced_progress"
    title="Waste Processing & Recycling"
    subtitle="Advanced • 6 lessons • Certificate on completion"
    accentColor="red"
    backTab="core-training"
    certParam="waste"
    introVideo={advancedVideo}
    lessons={lessons}
  />
);
